"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";

export function TdsGate({product,name,source="product-page",className="button gold"}:{product:string;name:string;source?:string;className?:string}){
  const dialog=useRef<HTMLDialogElement>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{const node=dialog.current;const close=(event:MouseEvent)=>{if(event.target===node)node?.close()};node?.addEventListener("click",close);return()=>node?.removeEventListener("click",close)},[]);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const form=new FormData(event.currentTarget);
    try{const response=await fetch("/api/tds-downloads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...Object.fromEntries(form.entries()),product,source})});const data=await response.json();if(!response.ok)throw new Error(data.error);dialog.current?.close();window.location.assign(data.downloadUrl);}catch(err){setError(err instanceof Error?err.message:"The document could not be opened.");}finally{setLoading(false)}}
  return <><button type="button" className={className} onClick={()=>dialog.current?.showModal()}>Download TDS <span aria-hidden>↓</span></button><dialog ref={dialog} className="tds-dialog" aria-labelledby={`tds-${product}`}><button className="dialog-close" type="button" onClick={()=>dialog.current?.close()} aria-label="Close">×</button><span className="section-index">Technical document</span><h2 id={`tds-${product}`}>Get the {name} TDS.</h2><p>Enter your name and mobile number to open the current official technical data sheet.</p><form onSubmit={submit}><label>Full name<input name="name" autoComplete="name" minLength={2} autoFocus required/></label><label>Mobile number<input name="mobile" type="tel" inputMode="tel" autoComplete="tel" placeholder="+91 98765 43210" required/></label><label className="honeypot" aria-hidden>Website<input name="website" tabIndex={-1}/></label><label className="consent-check"><input type="checkbox" required/><span>I agree that Resibond may contact me about this product. <Link href="/privacy" target="_blank">Privacy notice</Link>.</span></label><button className="button primary" disabled={loading} type="submit">{loading?"Preparing…":"Open TDS →"}</button>{error&&<p className="form-status error" role="alert">{error}</p>}</form></dialog></>;
}
